name: Publish

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
       description: 'OpenWrt version'
       default: '23.05.3'
       required: true
       type: string
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          #- arm_arm1176jzf-s_vfp # RPi Zero
          #- aarch64_cortex-a53   # RPi 3+
          - bcm27xx-bcm2710

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ github.event.inputs.openwrt_version }}
          V: sc
          PACKAGES: librespot

      - name: List outputs
        run: |
          find bin/packages

      - uses: actions/upload-artifact@v4
        with:
          name: ls-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/action/*.ipk

  release:

    name: Release all packages
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    
      - uses: actions/download-artifact@v4
        with:
          path: ipks
          merge-multiple: true
          
      - name: List outputs
        id: list
        run: |
          find ipks
          ls ipks | head -n 1 | awk -F"_" '{ print "librespot_version="$2 }' >> "$GITHUB_OUTPUT"
    
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.list.outputs.librespot_version }}_${{ github.event.inputs.openwrt_version }}_${{ github.run_number }}
          body: |
            Librespot v${{ steps.list.outputs.librespot_version }} OpenWrt ${{ github.event.inputs.openwrt_version }} build
          files: |
            ipks/*
