name: Compile librespot

on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm_arm1176jzf-s_vfp # RPi Zero
          - aarch64_cortex-a53   # RPi 3+
        version:
          - 23.05.2

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #- name: Build
      #  uses: openwrt/gh-action-sdk@main
      #  env:
      #    ARCH: ${{ matrix.arch }}-${{ matrix.version }}
      #    V: sc
      #    PACKAGES: librespot

      - name: List outputs
        run: |
          mkdir -p bin/packages/${{ matrix.arch }}/action
          touch bin/packages/${{ matrix.arch }}/action/empty-${{ matrix.arch }}.ipk
          find bin/packages

      - uses: actions/upload-artifact@v4
        with:
          name: ls-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/action/*.ipk
    
      #- name: Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    tag_name: ${{ matrix.version }}-${{ matrix.arch }}-${{ github.run_number }}
      #    body: |
      #      Librespot OpenWrt build
      #    files: |
      #      bin/packages/${{ matrix.arch }}/action/*.ipk
