name: Compile librespot

on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm_arm1176jzf-s_vfp

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: librespot

      - name: List outputs
        run: |
          find bin/packages
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ matrix.arch }}-${{ github.run_number }}
          body: |
            Librespot OpenWrt build
          files: |
            bin/packages/${{ matrix.arch }}/action/*.ipk
